---
application:
  name: "wechat2roam"
  project: "wechat2roam"
  organization: "QoveryCommunity"
routers:
- name: "main-wechat2roam"
  routes:
  - application_name: "wechat2roam"
    paths:
    - "/*"
